### ISSUE TITLE
Учесть замечания к предыдущим проектам

### ISSUE THREAD

**Issue by coursar** [DamirZaripov16/zodiac#1]
https://github.com/DamirZaripov16/gas

**Comment by DamirZaripov16** [comment]
Closed #1. @coursar тоже самое с CodeCov, но с 4-й линии
https://github.com/DamirZaripov16/zodiac/blob/d084be70e479bfc786b31c0ea0a67dd95d0a3f21/src/app/zodiac.js#L4-L27
